{{ $global := . }}
{{- if .Values.addresspools }}
{{- range $pool := .Values.addresspools }}
{{- if eq .protocol "layer2" }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ template "metallb.fullname" $global }}-{{ $pool.name }}
spec:
  ipAddressPools:
  - {{ template "metallb.fullname" $global }}-{{ $pool.name }}
  {{- if $pool.nodeSelectors }}
  nodeSelectors:
    {{- $pool.nodeSelectors | toYaml | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
